- go.mod
- go.sum
- tests/ibc_timeout_test.go
- tests/ibc_transfer_test.go
- tests/setup.go
Update rollup-e2e-testing framework
> Feat: Update testing framework

- tests/ibc_grace_period_test.go
- tests/ibc_timeout_test.go
- tests/ibc_transfer_test.go
- tests/setup.go
This PR:
- Set min_gas_price in feemarket genesis params to 0
- Change the time wait for blocks in order to make all transfer tests pass
> Fix all transfer tests

- Makefile
- go.mod
- go.sum
- tests/frozen_test.go
Partly close #33 
Description: 
- First set the DisputedPeriodBlocks to 50 through gov so that when submit fraud proposal, the gov will pass before state get finalized.
- Query latest state index, and when new latest state index appear, instantly submit fraud proposal through gov and vote yes.
- Check after 50 blocks, state index of Rollapp doesn't change and ibc transfer not working from both side
> Test Freeze Rollapp

- go.mod
- go.sum
- tests/rollapp_genesis_event_test.go
- tests/setup.go
> Add denommetadata check in rollapp_genesis_event_test

- tests/ibc_grace_period_test.go
> [Feat] Multiple rollapps e2e test for ibc grace period

- .github/workflows/e2e-test-evm-workflow-call.yml
- .github/workflows/e2e-test-wasm-workflow-call.yaml
- .github/workflows/e2e-test-workflow-call.yml
- .github/workflows/e2e_test.yml
- Makefile
- tests/rollapp_upgrade_test.go
- tests_spec/rollapp_upgrade.md
> Upgrade rollapp non state breaking

- Makefile
- go.mod
- go.sum
- tests/rollapp_genesis_event_test.go
Close a part of https://github.com/dymensionxyz/e2e-tests/issues/156 case 5
> test: rollapp-genesis ibc transfer from hub when only hub side gone through genesis

- tests/disconnection_test.go
- tests/eibc_ack_error_test.go
- tests/eibc_corrupted_memo_test.go
- tests/eibc_fee_test.go
- tests/eibc_fulfillment_test.go
- tests/eibc_invariant_test.go
- tests/eibc_nobalance_test.go
- tests/eibc_not_fulfillment_test.go
- tests/eibc_pfm_test.go
- tests/eibc_timeout_test.go
- tests/erc20_ibc_transfer_test.go
- tests/frozen_test.go
- tests/ibc_finalize_block_test.go
- tests/ibc_grace_period_test.go
- tests/ibc_pfm_test.go
- tests/ibc_pfm_with_grace_period_test.go
- tests/ibc_timeout_test.go
- tests/ibc_transfer_test.go
- tests/rollapp_genesis_event_test.go
- tests/rollapp_invariant_test.go
- tests/rollapp_upgrade_test.go
- tests/sequencer_invariant_test.go
- tests/setup.go
- tests/tx_batch_finalization_test.go
- tests/upgrade_hub_test.go
> chore: update dymint and go-relayer

- Makefile
- tests/frozen_test.go
> Feat(e2e): Add test for rollapp freeze non broken invariants

- Makefile
- tests/frozen_test.go
> Feat: ibc packet rollback on rollapp freeze

- Makefile
- tests/eibc_fulfillment_test.go
- tests/eibc_invariant_test.go
- tests/eibc_pfm_test.go
- tests/eibc_timeout_test.go
- tests/ibc_pfm_test.go
- tests/rollapp_genesis_event_test.go
- tests/upgrade_hub_test.go
> [test]: test cases ibc and eibc transfer after hub upgrade

- Makefile
- live-tests/eibc_no_memo_test.go
> test(live): Not specifying memo should not create demand order

- Makefile
- live-tests/ibc_transfer_test.go
> Feat(eibc): live test eibc fee  bigger than transfer amount should fail

- Makefile
- go.mod
- go.sum
- tests/hardfork_test.go
> [Test] E2E `Hard Fork` recover IBC client

- Makefile
- tests/genesis_transfer_test.go
> [E2E Test] Genesis transfers: bridge blocking

- Makefile
- tests/ibc_transfer_test.go
> [E2E Test] Genesis transfers: RA users cannot use reserved fungible packet memo

- Makefile
- tests/bridging_fee_test.go
> test(Bridging Fee): Non-rollapp chain <-> Hub unaffected by bridging fee middleware

- Makefile
- tests/bridging_fee_test.go
> [E2E Test] Bridging Fee: Change bridging fee param

- tests/eibc_ack_error_test.go
- tests/eibc_fulfillment_test.go
- tests/erc20_ibc_transfer_test.go
- tests/frozen_test.go
- tests/hardfork_test.go
- tests/ibc_grace_period_test.go
- tests/ibc_pfm_test.go
- tests/ibc_timeout_test.go
- tests/ibc_transfer_test.go
- tests/rollapp_upgrade_test.go
- tests/setup.go
The reason is that when disabling erc20, automated denom-metadata creation does not work.
> fix(tests): enable erc20 for all tests

- Makefile
- go.mod
- go.sum
- tests/admc_test.go
- tests/setup.go
> [E2E Test] ADMC: hub → rollapp. sending token that originates on the rollapp

- Makefile
- tests/admc_test.go
- tests/setup.go
> [E2E Test] ADMC: hub → rollapp - migrate denom, empty user memo

- Makefile
- tests/automated_denommetadata_test.go
> [E2E Test] ADMC: hub → rollapp - migrate “DYM”

- Makefile
- tests/admc_test.go
> [E2E Test] ADMC: hub → rollapp - migrate denom, denom metadata not found on hub

- Makefile
- go.mod
- go.sum
- tests/genesis_transfer_test.go
> [E2E Test] Genesis transfers: rollapp IBC connection blocking

- Makefile
- go.mod
- go.sum
- tests/eibc_feemarket_test.go
- tests/setup.go
> [E2E Test] EIBC Fee-Market: Changing existing demand order - Success

- Makefile
- go.mod
- go.sum
- tests/eibc_fee_market_test.go
> [E2E Test] EIBC Fee-Market: Changing existing DO - unallowed signer

- Makefile
- tests/automated_denommetadata_test.go
- tests/eibc_feemarket_test.go
> [E2E Test] EIBC Fee-Market: Updating demand order of AckErr and Timeout - Success

- Makefile
- tests/fullnode_sync_block_sync_test.go
- tests/setup.go
Suspend #367 Closes https://github.com/dymensionxyz/e2e-tests/issues/363
> Feat: Full-node syncs using block-sync - full node disconnects

- Makefile
- tests/canonical_light_client_test.go
> Canonical Light Client: rollapp has no light client defined 

- Makefile
- tests/sequencer_rotation_test.go
> [E2E Test] Sequencer Rotation last block produced, but last state update fails

- Makefile
- tests/sequencer_rotation_test.go
> [E2E Test] Sequencer Rotation historical sync - with sequencer change

- Makefile
- tests/sequencer_rotation_test.go
> [E2E Test] Sequencer Rotation historical sync - old sequencer already unbonded 

- Makefile
- tests/data/config.yaml
- tests/eibc_client_test.go
> [E2E Test] fulfills order that got polled, as the event was missed due to being offline

- Makefile
- tests/eibc_client_test.go
> [E2E-Test]: fulfills orders created by Rollapp A to HUB and Rollapp B to HUB transfers

- Makefile
- tests/eibc_client_test.go
> [E2E Test] does not fulfill order created by Rollapp A to HUB transfer, as it does not have DYM for fees

- Makefile
- tests/data/config.yaml
- tests/eibc_client_test.go
> [E2E Test] eibc-client fulfills order created by failed Acknowledgement from HUB to Rollapp A transfer

- go.mod
- go.sum
- tests/admc_test.go
- tests/data/native_denom.json
> fix (tests): revises genesis bridge

- Makefile
- tests/genesis_bridge_test.go
> [E2E Test] Genesis Bridge: Transfer from hub to rollapp before rollapp gets genesis bridge acknowledgement

- Makefile
- tests/fullnode_sync_test.go
- tests/sequencer_rotation_test.go
> [E2E Test] Sequencer Rotation: rotation request while submit already in progress

- Makefile
- go.mod
- go.sum
- tests/time_upgrade_test.go
- tests/zero_fee_relay_test.go
> [E2E Test] New sequencer relayer addresses can send free IBC txs

- Makefile
- tests/rollapp_state_update_test.go
> [E2E Test] Sequencer failure to write to settlement layer is recovered

- Makefile
- go.mod
- go.sum
- tests/genesis_bridge_test.go
- tests/setup.go
> [E2E Test] Try unbond sequencer before genesis bridge is opened

- Makefile
- tests/fraud_detection_test.go
- tests/setup.go
> [E2E Test] Fraud Detection: Block Gossiping Misbehavior (DA/P2P)

- Makefile
- go.mod
- go.sum
- tests/data/native_denom_tokenless.json
- tests/fullnode_sync_test.go
- tests/setup.go
- tests/time_upgrade_test.go
- tests/tokenless_test.go
> Add tokenless tests

- Makefile
- tests/fullnode_sync_test.go
- tests/rollapp_state_update_test.go
> [E2E Test] Full node syncing after multiple forks

- Makefile
- go.mod
- go.sum
- tests/data/config.yaml
- tests/eibc_ack_error_test.go
- tests/eibc_client_test.go
- tests/eibc_fee_market_test.go
- tests/eibc_feemarket_test.go
- tests/setup.go
> Add new testcase for eibc-client

- tests/eibc_ack_error_test.go
> [Update ]Update eIBC + DelayedAck tests

- tests/ibc_timeout_test.go
- Fix `TestIBCTransferTimeout_EVM` doesn't receive token after timeout `ibc transfer`
> [chores] fix `TestIBCTransferTimeout_EVM`

- tests/ibc_timeout_test.go
- tests/sequencer_rotation_test.go
* cleanup and removal of redundent code
* added r.UpdateClients to make timeout more detereministic
> fix(IBC timeout): fix IBC timeout test

- Makefile
- go.mod
- go.sum
- tests/erc20_ibc_transfer_test.go
- tests/setup.go
- tests/tokenless_test.go
> feat: add TestERC20StakingAndIBC_EVM
